# Generated by Django 2.1.2 on 2019-01-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=6)),
                ('solarSystem', models.TextField(null=True)),
                ('data', models.TextField()),
            ],
        ),
    ]
