# Generated by Django 2.1.2 on 2019-01-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscan', '0004_scan_summarytext'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='raw',
            field=models.TextField(null=True),
        ),
    ]
