# Generated by Django 2.1.2 on 2019-01-08 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterID', models.BigIntegerField(unique=True)),
                ('charName', models.CharField(max_length=200)),
                ('corpID', models.BigIntegerField()),
                ('corpName', models.CharField(max_length=200)),
                ('allianceID', models.BigIntegerField(null=True)),
                ('allianceName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EsiCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.TextField()),
                ('arguments', models.TextField()),
                ('cachedUntil', models.DateTimeField(null=True)),
                ('cachedResult', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InvGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.BigIntegerField(unique=True)),
                ('groupName', models.CharField(max_length=200)),
                ('capital', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeID', models.BigIntegerField(unique=True)),
                ('typeName', models.CharField(max_length=200)),
                ('group', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='esi.InvGroup', to_field='groupID')),
            ],
        ),
    ]
